### ISSUE TITLE
App highlighting

### ISSUE THREAD

**Issue by XBZ-1001** [B00merang-Project/Solaris-9#1]
Hi!
The app highlighting doesn't show which app is highlighted when using keyboard to navigate
![Using adwaita theme](https://user-images.githubusercontent.com/109128848/178414044-bd077ef1-a7d8-467f-a9d3-ad27eb5b1aae.png)
![Using Solaris 9 theme](https://user-images.githubusercontent.com/109128848/178414062-7f06bcac-9b9b-4a40-b662-cf0b459121cf.png)
.

**Comment by Elbullazul** [comment]
Which version of GNOME are you using?

**Comment by XBZ-1001** [comment]
3.38.5

**Comment by Elbullazul** [comment]
Should be fixed, please let me know if it doesn't.
