### ISSUE TITLE
Clarify compatible GTK versions

### ISSUE THREAD

**Issue by savchenko** [B00merang-Project/Solaris-9#2]
Azzurra framework Wiki specifies the [list of requirements](https://github.com/B00merang-Project/Azurra_framework/wiki/1.-Requirements) but does not mention compatible GTK versions.

For example, can this theme be used with Gnome 43 / libgtk 3.24+?

**Comment by Elbullazul** [comment]
Yes, this theme works with Gnome 43.

I used to keep a list of supported GTK versions before, but keeping it up-to-date across multiple repositories was very time-consuming. I'll try to come up with an idea to list supported versions in the coming weeks.

**Comment by Elbullazul** [comment]
I created a [list of supported environments](https://github.com/B00merang-Project/Azurra_framework/blob/master/SUPPORT.md) in the Azurra repo, I'll add references from the theme repos to it in the coming weeks.
